sequenceDiagram
participant Browser 
participant Server

Browser->>Server Get https://studies.cs.helsinki.fi/exampleapp/spa
activate server :  [{ "content": " ", "date": "2023-12-9" }, ... ]
server-->>browser: the HTML file
deactivate server



browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
activate server
server-->>browser: HTML file
deactivate server

browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
activate server
server-->>browser: the JavaScript file
deactivate server

Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server

browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
activate server
server-->>browser: [{ "content": "drgreg", "date": "2023-12-9" }, ... ]
deactivate server